In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('sort-minRange.csv')

In [4]:
df.head()

NORAD_CAT_ID_1      OBJECT_NAME_1  DSE_1  NORAD_CAT_ID_2  \
0           56423  STARLINK-6239 [+]  3.967           39432   
1           56046    ONEWEB-0537 [+]  5.103            7958   
2           45776  STARLINK-1489 [+]  7.437           30216   
3           57830  YAOGAN-40 01A [+]  3.738           57833   
4           45697  STARLINK-1351 [+]  5.173           35906   

         OBJECT_NAME_2  DSE_2                      TCA  TCA_RANGE  \
0          ICUBE-1 [-]  3.868  2023-11-16 19:13:55.776      0.000   
1      DELTA 1 DEB [-]  5.454  2023-11-18 08:28:04.088      0.023   
2   FENGYUN 1C DEB [-]  7.013  2023-11-19 22:59:57.502      0.027   
3    YAOGAN-40 01C [+]  3.525  2023-11-16 15:56:36.434      0.029   
4  COSMOS 2251 DEB [-]  5.322  2023-11-18 06:17:36.729      0.040   

   TCA_RELATIVE_SPEED  MAX_PROB  DILUTION  
0              13.333  1.000000     0.000  
1              12.637  0.015430     0.009  
2              14.572  0.023640     0.015  
3               0.098  0.005278     0.007  
4              13.533  0.013620     0.017

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67905 entries, 0 to 67904
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   NORAD_CAT_ID_1      67905 non-null  int64  
 1   OBJECT_NAME_1       67905 non-null  object 
 2   DSE_1               67905 non-null  float64
 3   NORAD_CAT_ID_2      67905 non-null  int64  
 4   OBJECT_NAME_2       67905 non-null  object 
 5   DSE_2               67905 non-null  float64
 6   TCA                 67905 non-null  object 
 7   TCA_RANGE           67905 non-null  float64
 8   TCA_RELATIVE_SPEED  67905 non-null  float64
 9   MAX_PROB            67905 non-null  float64
 10  DILUTION            67905 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 5.7+ MB


In [6]:
#CONVERT TCA to datetime

df['TCA'] = pd.to_datetime(df['TCA'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67905 entries, 0 to 67904
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   NORAD_CAT_ID_1      67905 non-null  int64         
 1   OBJECT_NAME_1       67905 non-null  object        
 2   DSE_1               67905 non-null  float64       
 3   NORAD_CAT_ID_2      67905 non-null  int64         
 4   OBJECT_NAME_2       67905 non-null  object        
 5   DSE_2               67905 non-null  float64       
 6   TCA                 67905 non-null  datetime64[ns]
 7   TCA_RANGE           67905 non-null  float64       
 8   TCA_RELATIVE_SPEED  67905 non-null  float64       
 9   MAX_PROB            67905 non-null  float64       
 10  DILUTION            67905 non-null  float64       
dtypes: datetime64[ns](1), float64(6), int64(2), object(2)
memory usage: 5.7+ MB


In [7]:
#Check for null values

df.isnull().sum()

NORAD_CAT_ID_1        0
OBJECT_NAME_1         0
DSE_1                 0
NORAD_CAT_ID_2        0
OBJECT_NAME_2         0
DSE_2                 0
TCA                   0
TCA_RANGE             0
TCA_RELATIVE_SPEED    0
MAX_PROB              0
DILUTION              0
dtype: int64

In [8]:
df.describe().T

count                           mean  \
NORAD_CAT_ID_1      67905.0                   48489.840424   
DSE_1               67905.0                       3.902143   
NORAD_CAT_ID_2      67905.0                    43693.96875   
DSE_2               67905.0                       4.303431   
TCA                   67905  2023-11-16 20:05:32.527137024   
TCA_RANGE           67905.0                       3.320069   
TCA_RELATIVE_SPEED  67905.0                      11.360936   
MAX_PROB            67905.0                       0.000026   
DILUTION            67905.0                       1.393364   

                                           min                            25%  \
NORAD_CAT_ID_1                           900.0                        43884.0   
DSE_1                                    0.091                          2.167   
NORAD_CAT_ID_2                            11.0                        32142.0   
DSE_2                                    0.097                          2.327   
TCA                 2023-11-13 08:00:06.086000  2023-11-15 02:14:33.775000064   
TCA_RANGE                                  0.0                           2.48   
TCA_RELATIVE_SPEED                         0.0                          8.939   
MAX_PROB                                   0.0                            0.0   
DILUTION                                   0.0                          0.881   

                                              50%                         75%  \
NORAD_CAT_ID_1                            48898.0                     53885.0   
DSE_1                                       3.905                       5.638   
NORAD_CAT_ID_2                            46483.0                     56208.0   
DSE_2                                       4.153                       5.937   
TCA                 2023-11-16 20:05:31.111000064  2023-11-18 13:56:55.204000   
TCA_RANGE                                   3.518                       4.322   
TCA_RELATIVE_SPEED                          12.89                      14.407   
MAX_PROB                                 0.000001                    0.000002   
DILUTION                                    1.261                       1.846   

                                           max           std  
NORAD_CAT_ID_1                         58255.0   7048.638537  
DSE_1                                   26.946      2.040112  
NORAD_CAT_ID_2                        270286.0  23495.061284  
DSE_2                                   35.977      2.721906  
TCA                 2023-11-20 07:59:43.237000           NaN  
TCA_RANGE                                  5.0      1.184498  
TCA_RELATIVE_SPEED                      16.894       3.79152  
MAX_PROB                                   1.0      0.003844  
DILUTION                                 3.533      0.710981

In [9]:
#Check for Duplicates

df.duplicated().value_counts()

False    67905
Name: count, dtype: int64

Descriptive Analytics


In [10]:
#Total Conjunctions

conjunctions = len(df)
print(f"Total Number of Conjuntions Active :{conjunctions}")

Total Number of Conjuntions Active :67905


In [11]:
#Active Satellites

active_satellites = df['NORAD_CAT_ID_1']._append(df['NORAD_CAT_ID_2']).unique()
print(f"Total Number of Active Satellites:{len(active_satellites)}")

Total Number of Active Satellites:15322


In [12]:
# Risk Management

low_risk = df[df['MAX_PROB'] < 0.05]
high_risk = df[df['MAX_PROB'] >= 0.05]

print(f"Low Risk Conjunctions: {len(low_risk)}")
print(f"High Risk Conjunctions: {len(high_risk)}")

Low Risk Conjunctions: 67904
High Risk Conjunctions: 1


Bar Graph showing High Risk Conjunctions and Low Risk Conjunctions


<img src="Sheet 1.png" width="500"/>

From the graph we get to know that on 16/11/2023 19:13:56 we have max probability of conjucntion

In [13]:
# Analysis for a single day

data = df[df['TCA'].dt.strftime('%Y-%m-%d') == '2023-11-16']
data.head(10)

NORAD_CAT_ID_1      OBJECT_NAME_1  DSE_1  NORAD_CAT_ID_2  \
0            56423  STARLINK-6239 [+]  3.967           39432   
3            57830  YAOGAN-40 01A [+]  3.738           57833   
5            54162  STARLINK-5273 [+]  3.696           28855   
18           45187  STARLINK-1225 [+]  3.803           57327   
23           49163  STARLINK-3088 [+]  2.883           28221   
31           53676  STARLINK-4621 [+]  3.363           15535   
38           49438  STARLINK-3044 [+]  3.650           24082   
72           43187        S-NET B [+]  3.858           57636   
74           43776   SPAWAR-CAL-R [+]  2.870           53675   
83           36834      YAOGAN 10 [+]  3.735           43641   

         OBJECT_NAME_2  DSE_2                     TCA  TCA_RANGE  \
0          ICUBE-1 [-]  3.868 2023-11-16 19:13:55.776      0.000   
3    YAOGAN-40 01C [+]  3.525 2023-11-16 15:56:36.434      0.029   
5         PSLV DEB [-]  5.806 2023-11-16 14:56:32.708      0.040   
18       OBJECT BB [-]  3.795 2023-11-16 22:32:17.834      0.078   
23        NAXING 1 [?]  3.084 2023-11-16 00:17:57.235      0.086   
31  COSMOS 249 DEB [-]  3.727 2023-11-16 00:17:11.340      0.093   
38     PEGASUS DEB [-]  3.165 2023-11-16 07:54:31.136      0.114   
72  STARLINK-30330 [+]  4.231 2023-11-16 19:54:40.135      0.148   
74   STARLINK-4617 [+]  3.368 2023-11-16 00:22:01.121      0.152   
83       SAOCOM 1A [+]  3.775 2023-11-16 20:57:15.765      0.166   

    TCA_RELATIVE_SPEED  MAX_PROB  DILUTION  
0               13.333  1.000000     0.000  
3                0.098  0.005278     0.007  
5               13.267  0.013800     0.017  
18              13.792  0.003376     0.036  
23               7.701  0.004679     0.023  
31              15.038  0.001720     0.058  
38              13.701  0.001602     0.051  
72              13.573  0.000108     0.065  
74              15.018  0.000610     0.101  
83              14.890  0.000058     0.107

In [14]:
data.describe().T

count                           mean  \
NORAD_CAT_ID_1      9744.0                   48481.457512   
DSE_1               9744.0                        3.56279   
NORAD_CAT_ID_2      9744.0                   43767.970956   
DSE_2               9744.0                       3.965379   
TCA                   9744  2023-11-16 12:01:15.205073152   
TCA_RANGE           9744.0                       3.332612   
TCA_RELATIVE_SPEED  9744.0                      11.356736   
MAX_PROB            9744.0                       0.000114   
DILUTION            9744.0                        1.39601   

                                           min                            25%  \
NORAD_CAT_ID_1                          1512.0                        43883.0   
DSE_1                                    2.751                          3.302   
NORAD_CAT_ID_2                            22.0                       31978.25   
DSE_2                                     2.75                          3.351   
TCA                 2023-11-16 00:00:04.339000  2023-11-16 06:02:32.730749952   
TCA_RANGE                                  0.0                          2.484   
TCA_RELATIVE_SPEED                       0.001                        8.87375   
MAX_PROB                                   0.0                            0.0   
DILUTION                                   0.0                        0.87975   

                                           50%                            75%  \
NORAD_CAT_ID_1                         48797.0                       53851.25   
DSE_1                                    3.559                          3.806   
NORAD_CAT_ID_2                         46256.0                        56213.0   
DSE_2                                    3.647                           3.96   
TCA                 2023-11-16 12:04:50.716000  2023-11-16 17:59:59.085250048   
TCA_RANGE                               3.5365                        4.32625   
TCA_RELATIVE_SPEED                     12.8635                        14.3675   
MAX_PROB                              0.000001                       0.000002   
DILUTION                                 1.263                          1.852   

                                           max           std  
NORAD_CAT_ID_1                         58224.0   7030.357678  
DSE_1                                    6.179      0.349297  
NORAD_CAT_ID_2                        270275.0  24176.990739  
DSE_2                                   32.364      1.745793  
TCA                 2023-11-16 23:59:51.588000           NaN  
TCA_RANGE                                  5.0      1.180125  
TCA_RELATIVE_SPEED                      16.894      3.761523  
MAX_PROB                                   1.0      0.010132  
DILUTION                                 3.516      0.710828

In [15]:
print(f"Total conjuction for 2023-11-16 : {len(data)}")

Total conjuction for 2023-11-16 : 9744


In [16]:
# Filtering Conjunction with max_prob = 1.0 

data[data['MAX_PROB'] == 1.0]

NORAD_CAT_ID_1      OBJECT_NAME_1  DSE_1  NORAD_CAT_ID_2 OBJECT_NAME_2  \
0           56423  STARLINK-6239 [+]  3.967           39432   ICUBE-1 [-]   

   DSE_2                     TCA  TCA_RANGE  TCA_RELATIVE_SPEED  MAX_PROB  \
0  3.868 2023-11-16 19:13:55.776        0.0              13.333       1.0   

   DILUTION  
0       0.0

Visualization showing Various Distribtution 

<img src="Dashboard.png" width="700"/>

In [20]:
# Analysis for a single satellite 

satellite_id = df[(df['NORAD_CAT_ID_1'] == 56423) | (df['NORAD_CAT_ID_2'] == 56423)]
satellite_id

NORAD_CAT_ID_1      OBJECT_NAME_1  DSE_1  NORAD_CAT_ID_2  \
0               56423  STARLINK-6239 [+]  3.967           39432   
11485           36596          SJ-12 [+]  3.091           56423   
30000           56423  STARLINK-6239 [+]  4.244           43763   
49587           56423  STARLINK-6239 [+]  4.363           40029   
53215           52935          DS-EO [+]  2.277           56423   

              OBJECT_NAME_2  DSE_2                     TCA  TCA_RANGE  \
0               ICUBE-1 [-]  3.868 2023-11-16 19:13:55.776      0.000   
11485     STARLINK-6239 [+]  3.402 2023-11-16 05:40:40.935      2.042   
30000  UPPER FREE FLYER [-]  3.929 2023-11-17 01:52:30.099      3.305   
49587        FLOCK 1C-2 [-]  4.315 2023-11-17 04:44:04.352      4.262   
53215     STARLINK-6239 [+]  2.462 2023-11-15 07:07:28.097      4.420   

       TCA_RELATIVE_SPEED      MAX_PROB  DILUTION  
0                  13.333  1.000000e+00     0.000  
11485              13.298  5.960000e-07     0.855  
30000               9.102  3.330000e-07     0.946  
49587              13.852  6.037000e-08     1.982  
53215               5.784  2.109000e-07     1.116

<img src="Sheet 6.png" width="600"/>

The dots on the graph shows the active conjunciotns on  5 dates for Satellite_id 56423

In [25]:
# Selecting Data of 5 days for checking Conjunction

mask = (df['TCA'] > '2023-11-15') & (df['TCA'] <= '2023-11-20')
df2 = df.loc[mask]
df2.head()

NORAD_CAT_ID_1      OBJECT_NAME_1  DSE_1  NORAD_CAT_ID_2  \
0           56423  STARLINK-6239 [+]  3.967           39432   
1           56046    ONEWEB-0537 [+]  5.103            7958   
2           45776  STARLINK-1489 [+]  7.437           30216   
3           57830  YAOGAN-40 01A [+]  3.738           57833   
4           45697  STARLINK-1351 [+]  5.173           35906   

         OBJECT_NAME_2  DSE_2                     TCA  TCA_RANGE  \
0          ICUBE-1 [-]  3.868 2023-11-16 19:13:55.776      0.000   
1      DELTA 1 DEB [-]  5.454 2023-11-18 08:28:04.088      0.023   
2   FENGYUN 1C DEB [-]  7.013 2023-11-19 22:59:57.502      0.027   
3    YAOGAN-40 01C [+]  3.525 2023-11-16 15:56:36.434      0.029   
4  COSMOS 2251 DEB [-]  5.322 2023-11-18 06:17:36.729      0.040   

   TCA_RELATIVE_SPEED  MAX_PROB  DILUTION  
0              13.333  1.000000     0.000  
1              12.637  0.015430     0.009  
2              14.572  0.023640     0.015  
3               0.098  0.005278     0.007  
4              13.533  0.013620     0.017

In [26]:
len(df2)

48549

In [27]:
df2.describe().T

count                           mean  \
NORAD_CAT_ID_1      48549.0                   48467.990443   
DSE_1               48549.0                       4.560607   
NORAD_CAT_ID_2      48549.0                   43699.381944   
DSE_2               48549.0                       4.959633   
TCA                   48549  2023-11-17 11:55:15.558629632   
TCA_RANGE           48549.0                       3.320067   
TCA_RELATIVE_SPEED  48549.0                      11.396536   
MAX_PROB            48549.0                       0.000031   
DILUTION            48549.0                       1.394442   

                                           min                            25%  \
NORAD_CAT_ID_1                           900.0                        43884.0   
DSE_1                                    1.802                          3.318   
NORAD_CAT_ID_2                            11.0                        32137.0   
DSE_2                                    1.756                          3.462   
TCA                 2023-11-15 00:00:01.562000  2023-11-16 06:03:17.353999872   
TCA_RANGE                                  0.0                          2.483   
TCA_RELATIVE_SPEED                       0.001                          8.991   
MAX_PROB                                   0.0                            0.0   
DILUTION                                   0.0                          0.883   

                                              50%  \
NORAD_CAT_ID_1                            48791.0   
DSE_1                                       4.553   
NORAD_CAT_ID_2                            46504.0   
DSE_2                                       4.766   
TCA                 2023-11-17 11:42:22.068999936   
TCA_RANGE                                   3.518   
TCA_RELATIVE_SPEED                         12.908   
MAX_PROB                                 0.000001   
DILUTION                                    1.264   

                                              75%                         max  \
NORAD_CAT_ID_1                            53850.0                     58227.0   
DSE_1                                       5.798                      26.946   
NORAD_CAT_ID_2                            56216.0                    270286.0   
DSE_2                                       6.057                      34.958   
TCA                 2023-11-18 17:50:05.198000128  2023-11-19 23:59:57.043000   
TCA_RANGE                                   4.324                         5.0   
TCA_RELATIVE_SPEED                         14.407                      16.894   
MAX_PROB                                 0.000002                         1.0   
DILUTION                                    1.846                       3.533   

                             std  
NORAD_CAT_ID_1         7025.8804  
DSE_1                   1.468486  
NORAD_CAT_ID_2      23467.262852  
DSE_2                   2.324496  
TCA                          NaN  
TCA_RANGE                 1.1859  
TCA_RELATIVE_SPEED      3.751261  
MAX_PROB                0.004544  
DILUTION                0.709334

<img src="Sheet 7.png" width="600"/>

This plot shows the value variation of TCA range and TCA relative speed over a period of 5 days

In [30]:
# Filtering with Satellite_id to check conjunction

satellite_id = df2[(df2['NORAD_CAT_ID_1'] == 56153) | (df2['NORAD_CAT_ID_2'] == 56153)]
print(satellite_id)

       NORAD_CAT_ID_1    OBJECT_NAME_1  DSE_1  NORAD_CAT_ID_2  OBJECT_NAME_2  \
6               56153     OBJECT A [+]  2.787           56154   OBJECT B [+]   
10              56153     OBJECT A [+]  2.853           56154   OBJECT B [+]   
28              56153     OBJECT A [+]  2.720           56154   OBJECT B [+]   
37              56153     OBJECT A [+]  2.919           56154   OBJECT B [+]   
65              56153     OBJECT A [+]  2.654           56154   OBJECT B [+]   
...               ...              ...    ...             ...            ...   
59921           56153     OBJECT A [+]  6.090           56154   OBJECT B [+]   
61890           55054  SKYKRAFT-1A [+]  3.842           56153   OBJECT A [+]   
63122           56153     OBJECT A [+]  6.156           56154   OBJECT B [+]   
66578           56153     OBJECT A [+]  6.222           56154   OBJECT B [+]   
66896           56153     OBJECT A [+]  3.057           57042  OBJECT AQ [+]   

       DSE_2                     TCA  T

In [31]:
len(satellite_id)

68

<img src="Sheet 8.png" width="600"/>

This plot graph shows conjunction grwoth and drop for  satellite_id 56153 for 5 days starting from 	13/11/2023 08:01:39 to 19/11/2023 19:53:08

